App.User = DS.Model.extend
  first_name: DS.attr()
  last_name: DS.attr()
  username: DS.attr()
  password: DS.attr()
  password_confirmation: DS.attr()
  email: DS.attr()
  website: DS.attr()
  avatar: DS.attr()
  work_time: DS.attr()
  break_time: DS.attr()
  pomodoros: DS.hasMany('pomodoro')
